---
- hosts: localhost
  tasks: 
    - name: Create Security Groups
      ec2_group:
        name: allow_80
        description: "sg with rule descriptions"
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0